Document: etcd
Title: Debian etcd Manual
Author: <insert document author here>
Abstract: This manual describes what etcd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/etcd/etcd.sgml.gz

Format: postscript
Files: /usr/share/doc/etcd/etcd.ps.gz

Format: text
Files: /usr/share/doc/etcd/etcd.text.gz

Format: HTML
Index: /usr/share/doc/etcd/html/index.html
Files: /usr/share/doc/etcd/html/*.html
